name: Build Android Project
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Build Project
        run: echo "Building Project"
